########################
#uOFFICE Beta build D1 #
#Demonstration         #
########################

'''
notes
[] Needs to be rewritten in C when my compiler program works again
[] Program is 64 bit, and strictly 64 bit. However, there will be a 128 bit edition in the future that is backwards compatibile with the x64 edition
[] 64 bit integer = 9,223,372,036,854,775,807 
[] 64 bit hexadecimal = 7FFF,FFFF,FFFF,FFFF 16
'''

print ("Startup console")
print ("Loading English dictionary")
dictionary1pass = int
dictionary1pass == 3264
print ("Loading Spanish dictionary")
dictionary2pass = int
dictionary2pass == 2264
print ("Loading French dictionary")
dictionary3pass = int
dictionary3pass == 7767
print ("Loading file containers")
udoct = int
udocs = int
udocm = int
udocw = int
print ("Startup console loaded")
print ("Select a product to open")
print ("uOffice Document Cabinet - Your standard Text Editing software from uOffice   | ID = 1")
print ("uOffice Spreaded Enterprise - Your standard Spreadsheet software from uOffice | ID = 2")
print ("uOffice Power Theater - Your standard presentation software from uOffice      | ID = 3")
print ("uOffice Megaweb - Your standard website editor from uOffice                   | ID = 4")
officeredirect1 = int(input("Product:"))
if (officeredirect1 == 1):
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print ("==================================================")
	print ("|                                                |")
	print ("| uOffice document cabinet                       |")
	print ("| Version 0.5.07                                 |")
	print ("| Demo edition 1                                 |")
	print ("| 2013-2018 Sean Walla Walla All Rights Reserved |")
	print ("|                                                |")
	print ("|                                                |")
	print ("==================================================")
	print (" ")
	print ("========================================================================================================================================================")
	print ("| Document Lobby                                                                                                                                        |")
	print ("|                                                                                                                                                       |")
	print ("| O P E N                                                                                                                                               |")
	print ("|                                                                                                                                                       |")
	print ("| Open DOC 1.0 file (8/16 bit compatibility mode)     | size limit: 8 Megabytes                                                                         |")
	print ("| Open DOC 2.0 file (8/16 bit compatibility mode)     | size limit: 16 Megabytes                                                                        |")
	print ("| Open DOC 3.0 file (8/16 bit compatibility mode)     | size limit: 32 Megabytes                                                                        |")
	print ("| Open DOC 4.0 file (16/32 bit compatibility mode)    | size limit: 64 Megabytes                                                                        |")
	print ("| Open DOC 5.0 file (16/32 bit compatibility mode)    | size limit: 64 Megabytes                                                                        |")
	print ("| Open DOC 6.0 file (16/32 bit compatibility mode)    | size limit: 64 Megabytes                                                                        |")
	print ("| Open DOCX file (32/64 bit compatibility mode)       | size limit: 512 Megabytes                                                                       |")
	print ("| Open TXT file (4/8/16/32/64 bit compatibility mode) | size limit: 4096 Megabytes                                                                      |")
	print ("| Open ODT file (16/32/64 bit compatibility mode      | size limit: 512 Megabytes                                                                       |")
	print ("| Open RTF file (8/16/32/64 bit compatibility mode    | size limit: 4096 Megabytes                                                                      |")
	print ("| Open UDOCT file (32/64 bit compatibility mode       | size limit: 1024 Petabytes                                                                      |")
	print ("|                                                                                                                                                       |")
	print ("| C R E A T E                                                                                                                                           |")
	print ("|                                                                                                                                                       |")
	print ("| New DOC 1.0 file (8/16 bit compatibility mode)     | size limit: 8 Megabytes                                                                          |")
	print ("| New DOC 2.0 file (8/16 bit compatibility mode)     | size limit: 16 Megabytes                                                                         |")
	print ("| New DOC 3.0 file (8/16 bit compatibility mode)     | size limit: 32 Megabytes                                                                         |")
	print ("| New DOC 4.0 file (16/32 bit compatibility mode)    | size limit: 64 Megabytes                                                                         |")
	print ("| New DOC 5.0 file (16/32 bit compatibility mode)    | size limit: 64 Megabytes                                                                         |")
	print ("| New DOC 6.0 file (16/32 bit compatibility mode)    | size limit: 64 Megabytes                                                                         |")
	print ("| New DOCX file (32/64 bit compatibility mode)       | size limit: 512 Megabytes                                                                        |")
	print ("| New TXT file (4/8/16/32/64 bit compatibility mode) | size limit: 4096 Megabytes                                                                       |")
	print ("| New ODT file (16/32/64 bit compatibility mode      | size limit: 512 Megabytes                                                                        |")
	print ("| New RTF file (8/16/32/64 bit compatibility mode    | size limit: 4096 Megabytes                                                                       |")
	print ("| New UDOCT file (32/64 bit compatibility mode       | size limit: 1024 Petabytes                                                                       |")
	print ("|                                                                                                                                                       |")
	print ("| S E T T I N G S                                                                                                                                       |")
	print ("|                                                                                                                                                       |")
	print ("| Export file | Read only mode | Publish file | Upload file | Repair file | Rollback file | View source of file | Open file location | Get file ID      |")
	print ("|                                                                                                                                                       |")
	print ("=========================================================================================================================================================")
if (officeredirect1 == 2):
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print ("==================================================")
	print ("|                                                |")
	print ("| uOffice spreaded enterprise                    |")
	print ("| Version 0.5.07                                 |")
	print ("| Demo edition 1                                 |")
	print ("| 2013-2018 Sean Walla Walla All Rights Reserved |")
	print ("|                                                |")
	print ("|                                                |")
	print ("==================================================")
	print (" ")
	print ("========================================================================================================================================================")
	print ("| Document Lobby                                                                                                                                        |")
	print ("|                                                                                                                                                       |")
	print ("| O P E N                                                                                                                                               |")
	print ("|                                                                                                                                                       |")
	print ("| Open XLS spreadsheet (8/16/32 bit compatibility mode)   | size limit: 8 Megabytes                                                                     |")
	print ("| Open XML file (8/16/32/64 bit compatibility mode)       | size limit: 256 Megabytes                                                                   |")
	print ("| Open XLW Workspace (8/16/32 bit compatibility mode)     | size limit: 8 Megabytes                                                                     |")
	print ("| Open XLSX spreadsheet (32/64 bit compatibility mode)    | size limit: 512 Megabytes                                                                   |")
	print ("| Open TXT document (4/8/16/32/64 bit compatibility mode) | size limit: 4096 Megabytes                                                                  |")
	print ("| Open UDOCS spreadsheet (32/64 bit compatibility mode)   | size limit: 1024 Petabytes                                                                  |")
	print ("| Open ODS spreadsheet (16/32/64 bit compatibility mode)  | size limit: 512 Megabytes                                                                   |")
	print ("| Open ZIP archive (8/16/32/64 bit compatibility mode)    | size limit: 128 Petabytes                                                                   |")
	print ("| Open CSV file (8/16/32/64 bit compatibility mode)       | size limit: 4096 Megabytes                                                                  |")
	print ("| Open XLC chart file (8/16/32 bit compatibility mode)    | size limit: 16 megabytes                                                                    |")
	print ("| Open DLL file (8/16/32/64 bit compatibility mode)       | size limit: 800 Gigabytes                                                                   |")
	print ("|                                                                                                                                                       |")
	print ("| C R E A T E                                                                                                                                           |")
	print ("|                                                                                                                                                       |")
	print ("| New XLS spreadsheet (8/16/32 bit compatibility mode)   | size limit: 8 Megabytes                                                                      |")
	print ("| New XML file (8/16/32/64 bit compatibility mode)       | size limit: 256 Megabytes                                                                    |")
	print ("| New XLW Workspace (8/16/32 bit compatibility mode)     | size limit: 8 Megabytes                                                                      |")
	print ("| New XLSX spreadsheet (32/64 bit compatibility mode)    | size limit: 512 Megabytes                                                                    |")
	print ("| New TXT document (4/8/16/32/64 bit compatibility mode) | size limit: 4096 Megabytes                                                                   |")
	print ("| New UDOCS spreadsheet (32/64 bit compatibility mode)   | size limit: 1024 Petabytes                                                                   |")
	print ("| New ODS spreadsheet (16/32/64 bit compatibility mode)  | size limit: 512 Megabytes                                                                    |")
	print ("| New ZIP archive (8/16/32/64 bit compatibility mode)    | size limit: 128 Petabytes                                                                    |")
	print ("| New CSV file (8/16/32/64 bit compatibility mode)       | size limit: 4096 Megabytes                                                                   |")
	print ("| New XLC chart file (8/16/32 bit compatibility mode)    | size limit: 16 megabytes                                                                     |")
	print ("| New DLL file (8/16/32/64 bit compatibility mode)       | size limit: 800 Gigabytes                                                                    |")
	print ("|                                                                                                                                                       |")
	print ("| S E T T I N G S                                                                                                                                       |")
	print ("|                                                                                                                                                       |")
	print ("| Export file | Read only mode | Publish file | Upload file | Repair file | Rollback file | View source of file | Open file location | Get file ID      |")
	print ("|                                                                                                                                                       |")	
	print ("=========================================================================================================================================================")
if (officeredirect1 == 3):
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print ("==================================================")
	print ("|                                                |")
	print ("| uOffice Star theater                           |")
	print ("| Version 0.5.07                                 |")
	print ("| Demo edition 1                                 |")
	print ("| 2013-2018 Sean Walla Walla All Rights Reserved |")
	print ("|                                                |")
	print ("|                                                |")
	print ("==================================================")
	print (" ")
	print ("========================================================================================================================================================")
	print ("| Document Lobby                                                                                                                                        |")
	print ("|                                                                                                                                                       |")
	print ("| O P E N                                                                                                                                               |")
	print ("|                                                                                                                                                       |")
	print ("| Open PPT 1.0 presentation (8 bit compatibility mode)       | size limit: 8 Megabytes                                                                  |")
	print ("| Open PPT 2.0 presentation (8/16 bit compatibility mode)    | size limit: 8 Megabytes                                                                  |")
	print ("| Open PPT 3.0 presentation (8/16 bit compatibility mode)    | size limit: 16 Megabytes                                                                 |")
	print ("| Open PPT 4.0 presentation (8/16/32 bit compatibility mode) | size limit: 32 Megabytes                                                                 |")
	print ("| Open PPT 5.0 presentation (8/16/32 bit compatibility mode) | size limit: 64 Megabytes                                                                 |")
	print ("| Open PPT 6.0 presentation (8/16/32 bit compatibility mode) | size limit: 64 Megabytes                                                                 |")
	print ("| Open POT Template (8/16/32 bit compatibility mode)         | size limit: 4 Megabytes                                                                  |")
	print ("| Open PPTX presentation (32/64 bit compatibility mode)      | size limit: 512 Megabytes                                                                |")
	print ("| Open ODP presentation (32/64 bit compatibility mode)       | size limit: 512 Megabytes                                                                |")
	print ("| Open WMMP project (32/64 bit compatibility mode)           | size limit: 256 Megabytes                                                                |")
	print ("| Open WLMP project (32/64 bit compatibility mode)           | size limit: 512 Megabytes                                                                |")
	print ("| Open WP3 project (32/64 bit compatibility mode)            | size limit: 1024 Megabytes                                                               |")
	print ("|                                                                                                                                                       |")
	print ("| C R E A T E                                                                                                                                           |")
	print ("|                                                                                                                                                       |")
	print ("| New PPT 1.0 presentation (8 bit compatibility mode)       | size limit: 8 Megabytes                                                                   |")
	print ("| New PPT 2.0 presentation (8/16 bit compatibility mode)    | size limit: 8 Megabytes                                                                   |")
	print ("| New PPT 3.0 presentation (8/16 bit compatibility mode)    | size limit: 16 Megabytes                                                                  |")
	print ("| New PPT 4.0 presentation (8/16/32 bit compatibility mode) | size limit: 32 Megabytes                                                                  |")
	print ("| New PPT 5.0 presentation (8/16/32 bit compatibility mode) | size limit: 64 Megabytes                                                                  |")
	print ("| New PPT 6.0 presentation (8/16/32 bit compatibility mode) | size limit: 64 Megabytes                                                                  |")
	print ("| New POT Template (8/16/32 bit compatibility mode)         | size limit: 4 Megabytes                                                                   |")
	print ("| New PPTX presentation (32/64 bit compatibility mode)      | size limit: 512 Megabytes                                                                 |")
	print ("| New ODP presentation (32/64 bit compatibility mode)       | size limit: 512 Megabytes                                                                 |")
	print ("| New WMMP project (32/64 bit compatibility mode)           | size limit: 256 Megabytes                                                                 |")
	print ("| New WLMP project (32/64 bit compatibility mode)           | size limit: 512 Megabytes                                                                 |")
	print ("| New WP3 project (32/64 bit compatibility mode)            | size limit: 1024 Megabytes                                                                |")	
	print ("|                                                                                                                                                       |")      
	print ("| S E T T I N G S                                                                                                                                       |")
	print ("|                                                                                                                                                       |")
	print ("| Export file | Read only mode | Publish file | Upload file | Repair file | Rollback file | View source of file | Open file location | Get file ID      |")
	print ("|                                                                                                                                                       |")
	print ("=========================================================================================================================================================")
if (officeredirect1 == 4):
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print ("==================================================")
	print ("|                                                |")
	print ("| uOffice Megaweb                                |")
	print ("| Version 0.5.07                                 |")
	print ("| Demo edition 1                                 |")
	print ("| 2013-2018 Sean Walla Walla All Rights Reserved |")
	print ("|                                                |")
	print ("|                                                |")
	print ("==================================================")
	print (" ")
	print ("========================================================================================================================================================")
	print ("| Document Lobby                                                                                                                                        |")
	print ("|                                                                                                                                                       |")
	print ("| O P E N                                                                                                                                               |")
	print ("|                                                                                                                                                       |")
	print ("| Import from Google sites                                                                                                                              |")
	print ("| Import from Wix                                                                                                                                       |")
	print ("| Import from Tumblr                                                                                                                                    |")
	print ("| Recent folder                                                                                                                                         |")
	print ("| UDOCW file (32/64 bit compatibility mode)    | size limit: 2048 Petabytes                                                                             |")
	print ("| HTML file (16/32/64 bit compatibility mode)  | size limit: 1024 Gigabytes                                                                             |")
	print ("| XML file (8/16/32/64 bit compatibility mode) | size limit: 1024 Megabytes                                                                             |")
	print ("| JS file (16/32/64 bit compatibility mode)    | size limit: 1024 Megabytes                                                                             |")
	print ("| FLA FILE (16/32/64 bit compatibility mode)   | size limit: 128 Megabytes                                                                              |")
	print ("| MHTML file (16/32/64 bit compatibility mode) | size limit: 256 Megabytes                                                                              |")
	print ("| JSON file (16/32/64 bit compatibility mode)  | size limit: 256 Megabytes                                                                              |")
	print ("|                                                                                                                                                       |")
	print ("| C R E A T E                                                                                                                                           |")
	print ("|                                                                                                                                                       |")
	print ("| UDOCW file (32/64 bit compatibility mode)     | size limit: 2048 Petabytes                                                                            |")
	print ("| HTML file (16/32/64 bit compatibility mode)   | size limit: 1024 Gigabytes                                                                            |")
	print ("| XML file (8/16/32/64 bit compatibility mode)  | size limit: 1024 Megabytes                                                                            |")
	print ("| JS file (16/32/64 bit compatibility mode)     | size limit: 1024 Megabytes                                                                            |")
	print ("| FLA FILE (16/32/64 bit compatibility mode)    | size limit: 128 Megabytes                                                                             |")
	print ("| MHTML file (16/32/64 bit compatibility mode)  | size limit: 256 Megabytes                                                                             |")
	print ("| JSON file (16/32/64 bit compatibility mode)   | size limit: 256 Megabytes                                                                             |")
	print ("| HTM file (16/32/64 bit compatibility mode)    | size limit: 256 Megabytes                                                                             |")
	print ("| MHTM file (16/32/64 bit compatibility mode)   | size limit: 300 Megabytes                                                                             |")
	print ("| ZIP archive (16/32/64 bit compatibility mode) | size limit: 256 Petabytes                                                                             |")
	print ("| TAR file (16/32/64 bit compatibility mode)    | size limit: 128 Petabytes                                                                             |")
	print ("|                                                                                                                                                       |")
	print ("| S E T T I N G S                                                                                                                                       |")
	print ("|                                                                                                                                                       |")
	print ("| Export file | Read only mode | Publish file | Upload file | Repair file | Rollback file | View source of file | Open file location | Get file ID      |")
	print ("| Get HTTPS   | Remove HTTPS   | Get domain   | Server host | Offline     | Online        | View snapshots      | Get licensing info | View as guest    |")	
	print ("=========================================================================================================================================================")	
print ("Do you wish to exit your uOffice Beta Developer session?")
endses = int(input("Type 1 to quit, type anything else to crash"))
if endses == 1:
	print ("See you later!")
'''
special feature 1: Swear dictionary
turn the swear dictionary on and off when spellchecking. When this dictionary is active, recommendations for words can contain cursing
'''

'''
special feature 2: 
'''

'''
file container definitions:
UDOCT = Ultra document text - A text editor for Uoffice pro
UDOCS = Ultra document spreadhseet - A spreadsheet editor for Uoffice pro
UDOCM = Ultra document Movie - A presentation editor for Uoffice pro
UDOCW = Ultra document website - A website editor for Uoffice pro
capacity:
UDOCTT 
size: 2 Exabytes
Words: 32,648,228,430

'''
